### ISSUE TITLE
Homebrew

### ISSUE THREAD

**Issue by KofiMatson123** [projectpokemon/PPSE-DS#1]
Does this work on homebrew? 2017? For gen 4 games? For new3dsxl?

**Comment by Chase-san** [comment]
This is/was a tool for DS Flashcarts. It does not to my knowledge work as a 3ds homebrew.

**Comment by evandixon** [comment]
It _might_ work with [TWL Loader](https://gbatemp.net/threads/twloader-ctr-mode-nds-app.448375/), but I haven't tried.  Some things work and some things don't, so it's worth a try, but don't be surprised if it doesn't work.

**Comment by Chase-san** [comment]
Here is the most recent actual release iirc. http://csdgn.org/project_ppseds.html
